const features = [
  {
    title: 'LP NFT Collateral Support',
    details:
      'Support borrowing using Uniswap LP NFTs as collateral, activating LP asset liquidity and enabling flexible position adjustments and leveraged operations.\n\nThrough a collateral-based model, reduce gas costs generated by unnecessary position adjustments.',
  },
  {
    title: 'Adjustable & Controllable Interest Rates',
    details:
      'Interest rates can be optimized and controlled, breaking rigid uniform pricing models and providing clearer cost expectations across different lending scenarios.\n\nBuilt-in refinancing functionality enables access to more favorable rates as market conditions change.',
  },
  {
    title: 'Leveraged LP Yield',
    details:
      'Provide flexible leverage (1.1×–20×) for Uniswap LP positions to amplify yield opportunities.\n\nReal-time monitoring of position health factors, with multiple strategies to reduce liquidation risk.',
  },
  {
    title: 'Improved Capital Utilization',
    details:
      'Peer-to-peer matching model increases overall capital efficiency and minimizes idle liquidity.\n\nHence higher earnings for suppliers and lower costs for borrowers.',
  },
]

export default function Home() {
  return (
    <>
      {/* Hero */}
      <section className="max-w-[1152px] mx-auto px-6 pt-24 pb-20">
        <p
          className="text-5xl md:text-[56px] font-bold leading-tight tracking-tight mb-2"
          style={{
            backgroundImage: 'linear-gradient(120deg, #ffb74d, #d6711b)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            backgroundClip: 'text',
          }}
        >
          Constant Finance
        </p>
        <h1 className="text-5xl md:text-[56px] font-bold leading-tight tracking-tight text-[#213547] dark:text-[rgba(255,255,245,0.86)]">
          Reshaping the infrastructure of{' '}
          <span style={{ color: '#5672cd' }}>DeFi lending</span>
        </h1>
      </section>

      {/* Features */}
      <section className="max-w-[1152px] mx-auto px-6 pb-24 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {features.map((f) => (
          <div key={f.title} className="bg-[#f6f6f7] dark:bg-[#252529] rounded-xl p-6">
            <h2 className="text-sm font-semibold text-gray-900 dark:text-[rgba(255,255,245,0.86)] mb-3">{f.title}</h2>
            <div className="text-sm text-gray-600 dark:text-[rgba(235,235,245,0.6)] leading-relaxed space-y-3">
              {f.details.split('\n\n').map((para, i) => (
                <p key={i}>{para}</p>
              ))}
            </div>
          </div>
        ))}
      </section>
    </>
  )
}
